[package]
name = "tinyanvil"
version = "0.5.1"
edition = "2021"
description = "Hammer out customized tinystorm goldens: CoW base + host-side dnf delta, sealed by stormblock"
license = "MIT"
repository = "https://github.com/glennswest/tinyanvil"

[dependencies]

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"
